using SageOneApi.Client.Models;
using SageOneApi.Client.Models.Core;
using SageOneApi.Client.Responses;
using System.Text.Json.Serialization;

namespace SageOneApi.Client
{
    [JsonSourceGenerationOptions(WriteIndented = true)]

    [JsonSerializable(typeof(GetAllResponse<Address>))]
    [JsonSerializable(typeof(GetAllResponse<Address>))]
    [JsonSerializable(typeof(GetAllResponse<AllocatedArtefact>))]
    [JsonSerializable(typeof(GetAllResponse<Artefact>))]
    [JsonSerializable(typeof(GetAllResponse<AnalysisType>))]
    [JsonSerializable(typeof(GetAllResponse<AnalysisTypeCategory>))]
    [JsonSerializable(typeof(GetAllResponse<AnalysisTypeLevel>))]
    [JsonSerializable(typeof(GetAllResponse<Attachment>))]
    [JsonSerializable(typeof(GetAllResponse<BalanceDetails>))]
    [JsonSerializable(typeof(GetAllResponse<BankAccount>))]
    [JsonSerializable(typeof(GetAllResponse<BankAccountDetails>))]
    [JsonSerializable(typeof(GetAllResponse<BankReconciliation>))]
    [JsonSerializable(typeof(GetAllResponse<BankTransfer>))]
    [JsonSerializable(typeof(GetAllResponse<Business>))]
    [JsonSerializable(typeof(GetAllResponse<BusinessSettings>))]
    [JsonSerializable(typeof(GetAllResponse<CatalogItem>))]
    [JsonSerializable(typeof(GetAllResponse<CisSettings>))]
    [JsonSerializable(typeof(GetAllResponse<Contact>))]
    [JsonSerializable(typeof(GetAllResponse<ContactAllocation>))]
    [JsonSerializable(typeof(GetAllResponse<ContactPayment>))]
    [JsonSerializable(typeof(GetAllResponse<ContactPerson>))]
    [JsonSerializable(typeof(GetAllResponse<ControlTransaction>))]
    [JsonSerializable(typeof(GetAllResponse<ControlTransactionLine>))]
    [JsonSerializable(typeof(GetAllResponse<DatedTransaction>))]
    [JsonSerializable(typeof(GetAllResponse<DefaultLedgerAccounts>))]
    [JsonSerializable(typeof(GetAllResponse<FinancialSettings>))]
    [JsonSerializable(typeof(GetAllResponse<Journal>))]
    [JsonSerializable(typeof(GetAllResponse<JournalCode>))]
    [JsonSerializable(typeof(GetAllResponse<JournalLine>))]
    [JsonSerializable(typeof(GetAllResponse<LedgerAccount>))]
    [JsonSerializable(typeof(GetAllResponse<LedgerEntry>))]
    [JsonSerializable(typeof(GetAllResponse<Link>))]
    [JsonSerializable(typeof(GetAllResponse<OtherPayment>))]
    [JsonSerializable(typeof(GetAllResponse<PaymentLine>))]
    [JsonSerializable(typeof(GetAllResponse<PaymentOnAccount>))]
    [JsonSerializable(typeof(GetAllResponse<PropertyValue>))]
    [JsonSerializable(typeof(GetAllResponse<PropertyValueWithPath>))]
    [JsonSerializable(typeof(GetAllResponse<Product>))]
    [JsonSerializable(typeof(GetAllResponse<ProductSalesPrice>))]
    [JsonSerializable(typeof(GetAllResponse<PurchaseCreditNote>))]
    [JsonSerializable(typeof(GetAllResponse<PurchaseInvoice>))]
    [JsonSerializable(typeof(GetAllResponse<PurchaseQuickEntry>))]
    [JsonSerializable(typeof(GetAllResponse<PurchaseTransaction>))]
    [JsonSerializable(typeof(GetAllResponse<PurchaseTransactionLine>))]
    [JsonSerializable(typeof(GetAllResponse<QuickEntry>))]
    [JsonSerializable(typeof(GetAllResponse<SageOneAccountingEntity>))]
    [JsonSerializable(typeof(GetAllResponse<SageOneSingleAccountingEntity>))]
    [JsonSerializable(typeof(GetAllResponse<SalesCreditNote>))]
    [JsonSerializable(typeof(GetAllResponse<SalesInvoice>))]
    [JsonSerializable(typeof(GetAllResponse<SalesQuickEntry>))]
    [JsonSerializable(typeof(GetAllResponse<SalesTransaction>))]
    [JsonSerializable(typeof(GetAllResponse<SalesTransactionLine>))]
    [JsonSerializable(typeof(GetAllResponse<Service>))]
    [JsonSerializable(typeof(GetAllResponse<ServiceSalesRate>))]
    [JsonSerializable(typeof(GetAllResponse<StockItem>))]
    [JsonSerializable(typeof(GetAllResponse<Tax>))]
    [JsonSerializable(typeof(GetAllResponse<TaxAnalysis>))]
    [JsonSerializable(typeof(GetAllResponse<TaxPercentage>))]
    [JsonSerializable(typeof(GetAllResponse<TaxRate>))]
    [JsonSerializable(typeof(GetAllResponse<TaxTreatment>))]
    [JsonSerializable(typeof(GetAllResponse<Transaction>))]
    [JsonSerializable(typeof(GetAllResponse<TransactionType>))]

    [JsonSerializable(typeof(Business))]
    [JsonSerializable(typeof(Me))]
    [JsonSerializable(typeof(SageOneCoreEntity))]
    [JsonSerializable(typeof(Subscription))]
    [JsonSerializable(typeof(User))]

    [JsonSerializable(typeof(Address))]
    [JsonSerializable(typeof(Address))]
    [JsonSerializable(typeof(AllocatedArtefact))]
    [JsonSerializable(typeof(AnalysisType))]
    [JsonSerializable(typeof(AnalysisTypeCategory))]
    [JsonSerializable(typeof(AnalysisTypeLevel))]
    [JsonSerializable(typeof(Artefact))]
    [JsonSerializable(typeof(Attachment))]
    [JsonSerializable(typeof(BalanceDetails))]
    [JsonSerializable(typeof(BankAccount))]
    [JsonSerializable(typeof(BankAccountDetails))]
    [JsonSerializable(typeof(BankReconciliation))]
    [JsonSerializable(typeof(BankTransfer))]
    [JsonSerializable(typeof(BusinessSettings))]
    [JsonSerializable(typeof(CatalogItem))]
    [JsonSerializable(typeof(CisSettings))]
    [JsonSerializable(typeof(Contact))]
    [JsonSerializable(typeof(ContactAllocation))]
    [JsonSerializable(typeof(ContactPayment))]
    [JsonSerializable(typeof(ContactPerson))]
    [JsonSerializable(typeof(ControlTransaction))]
    [JsonSerializable(typeof(ControlTransactionLine))]
    [JsonSerializable(typeof(DatedTransaction))]
    [JsonSerializable(typeof(DefaultLedgerAccounts))]
    [JsonSerializable(typeof(FinancialSettings))]
    [JsonSerializable(typeof(Journal))]
    [JsonSerializable(typeof(JournalCode))]
    [JsonSerializable(typeof(JournalLine))]
    [JsonSerializable(typeof(LedgerAccount))]
    [JsonSerializable(typeof(LedgerEntry))]
    [JsonSerializable(typeof(Link))]
    [JsonSerializable(typeof(OtherPayment))]
    [JsonSerializable(typeof(PaymentLine))]
    [JsonSerializable(typeof(PaymentOnAccount))]
    [JsonSerializable(typeof(PropertyValue))]
    [JsonSerializable(typeof(PropertyValueWithPath))]
    [JsonSerializable(typeof(Product))]
    [JsonSerializable(typeof(ProductSalesPrice))]
    [JsonSerializable(typeof(PurchaseCreditNote))]
    [JsonSerializable(typeof(PurchaseInvoice))]
    [JsonSerializable(typeof(PurchaseQuickEntry))]
    [JsonSerializable(typeof(PurchaseTransaction))]
    [JsonSerializable(typeof(PurchaseTransactionLine))]
    [JsonSerializable(typeof(QuickEntry))]
    [JsonSerializable(typeof(SageOneAccountingEntity))]
    [JsonSerializable(typeof(SageOneSingleAccountingEntity))]
    [JsonSerializable(typeof(SalesCreditNote))]
    [JsonSerializable(typeof(SalesInvoice))]
    [JsonSerializable(typeof(SalesQuickEntry))]
    [JsonSerializable(typeof(SalesTransaction))]
    [JsonSerializable(typeof(SalesTransactionLine))]
    [JsonSerializable(typeof(Service))]
    [JsonSerializable(typeof(ServiceSalesRate))]
    [JsonSerializable(typeof(StockItem))]
    [JsonSerializable(typeof(Tax))]
    [JsonSerializable(typeof(TaxAnalysis))]
    [JsonSerializable(typeof(TaxPercentage))]
    [JsonSerializable(typeof(TaxRate))]
    [JsonSerializable(typeof(TaxTreatment))]
    [JsonSerializable(typeof(Transaction))]
    [JsonSerializable(typeof(TransactionType))]

    [JsonSerializable(typeof(OAuth2TokenResponse))]

    public partial class SourceGenerationContext : JsonSerializerContext
    { }
}
